### ISSUE TITLE
Wrong annotation to manager a cluster by clusterwide operator

### ISSUE THREAD

**Issue by plafosse-orange** [Orange-OpenSource/galera-operator#11]
In the example deployment file `40-galera.yaml`  , it is indicated
```yaml
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
   annotations:
    sql.databases/scope: clusterwide 
```
But this annotation is incorrect for it to work you have to put
```yaml
  annotations:
    galera.v1beta2sql.databases/scope: clusterwide
```
