### ISSUE TITLE
Deployment stuck at "Desired 3" - "Current 0"

### ISSUE THREAD

**Issue by God-Zalo** [Orange-OpenSource/galera-operator#13]
Followed the instructions at the `examples-manifests`, using "Three member cluster" example, galera-operator is deployed using the kustomize found in #12 

Then manually running `kubectl create -f   <galera-cluster>.yaml` deployment get stuck at `Desired 3 - Current 0`

This is what I could get my hands on:

galera-operator check:
```
kubectl get deployments.apps --namespace galera
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
galera-operator   1/1     1            1           62m

```

crd's check:
```
$ kubectl get crd
NAME                           CREATED AT
addons.k3s.cattle.io           2020-09-30T00:37:13Z
helmcharts.helm.cattle.io      2020-09-30T00:37:13Z
galeras.sql.databases          2020-09-30T00:38:01Z
galerabackups.sql.databases    2020-09-30T00:39:26Z
upgradeconfigs.sql.databases   2020-09-30T00:39:27Z
upgraderules.sql.databases     2020-09-30T00:40:01Z

```

Config map is embebed with yaml below, using the default provided in the spec example, nothing changed, 

Full yaml (skipping configmap data):
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: galeraconf
  namespace: galera
data:
...

---
apiVersion: sql.databases/v1beta2
kind: Galera
metadata:
  name: zalo1
  namespace: galera
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  #annotations:
  #  sql.databases/scope: clusterwide
  labels:
    stage: dev
    owner: sebs42
spec:
  replicas: 3
  pod:
    credentialsSecret:
      name: galera-secret
    image: sebs42/mariadb:10.4.2-bionic
    mycnfConfigMap:
      name: galeraconf
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: $ROOTPASSWORD
  persistentVolumeClaimSpec:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: $STORAGECLASS
    resources:
      requests:
        storage: 5Gi
```

Outputs:
```
NAMESPACE   NAME    DESIRED   CURRENT   AGE   PHASE   IMAGE                          METRICIMAGE   SPECIAL
galera      zalo1   3                   23m           sebs42/mariadb:10.4.2-bionic                 

```

Description of cluster deployment:
```
$ kubectl describe galeras.sql.databases/zalo1 --namespace galera
Name:         zalo1
Namespace:    galera
Labels:       owner=sebs42
              stage=dev
Annotations:  <none>
API Version:  sql.databases/v1beta2
Kind:         Galera
Metadata:
  Creation Timestamp:  2020-09-30T00:48:21Z
  Generation:          1
  Managed Fields:
    API Version:  sql.databases/v1beta2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:owner:
          f:stage:
      f:spec:
        .:
        f:persistentVolumeClaimSpec:
          .:
          f:accessModes:
          f:resources:
            .:
            f:requests:
              .:
              f:storage:
          f:storageClassName:
        f:pod:
          .:
          f:credentialsSecret:
            .:
            f:name:
          f:env:
          f:image:
          f:mycnfConfigMap:
            .:
            f:name:
        f:replicas:
    Manager:      kubectl-create
    Operation:    Update
    Time:         2020-09-30T00:48:21Z
    API Version:  sql.databases/v1beta2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2020-09-30T00:57:57Z
  Resource Version:  1794
  Self Link:         /apis/sql.databases/v1beta2/namespaces/galera/galeras/zalo1
  UID:               84b75575-9646-41b6-81c5-6ffdcfd7098f
Spec:
  Persistent Volume Claim Spec:
    Access Modes:
      ReadWriteOnce
    Resources:
      Requests:
        Storage:         5Gi
    Storage Class Name:  $STORAGECLASS
  Pod:
    Credentials Secret:
      Name:  galera-secret
    Env:
      Name:   MYSQL_ROOT_PASSWORD
      Value:  $ROOTPASSWORD
    Image:    sebs42/mariadb:10.4.2-bionic
    Mycnf Config Map:
      Name:  galeraconf
  Replicas:  3
Events:      <none>
```

The only error message found was with: 
```
$ kubectl logs galeras.sql.databases/zalo1 --namespace galera
error: no kind "Galera" is registered for version "sql.databases/v1beta2" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```
